language: cpp
os: linux
compiler: gcc
dist: trusty

before_install:
    # Add repository for Qt
    - sudo apt-add-repository --yes ppa:beineri/opt-qt-5.10.1-trusty
    - sudo apt-get -qq update
    
install:
    # Install needed Qt modules
    - sudo apt-get --yes install qt510base qt510svg
    
before_script:
    # Set Qt variables
    - QTDIR="/opt/qt510"
    - PATH="$QTDIR/bin:$PATH"
    - source /opt/qt510/bin/qt510-env.sh
    
    # Clone atools
    - git clone --branch=feature/ci https://github.com/prinz7/atools.git ../atools
    
script:
    # Build atools
    - mkdir ../build-atools-release
    - cd ../build-atools-release
    - qmake ../atools/atools.pro CONFIG+=release
    - make
    
    # Build littlenavmap
    - mkdir ../build-littlenavmap-release
    - cd ../build-littlenavmap-release
    - qmake ../littlenavmap/littlenavmap.pro CONFIG+=release
    - make
